volumes:
  postgresql_data:
  ldap_data:
  ldap_config:
  ldap_run:
  geoserver_geodata:
  geoserver_datadir:
  geoserver_tiles:
  geoserver_native_libs:
  mapstore_extensions:
  geonetwork_datadir:
  datafeeder_uploads:
  datafeeder_postgis_data:
  esdata:
  smtp_maildir:
  mail:
  mail_spool:

secrets:
  slapd_password:
    file: ./secrets/slapd_password.txt

services:
  caddy:
    image: caddy:2.8-alpine
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:2019:2019"
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    volumes:
      - ./resources/ssl:/etc/certs:ro
      - ./resources/caddy/etc:/etc/caddy:ro
      - ./resources/caddy/data:/data/caddy
      - ./resources/static:/usr/share/caddy/static:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:2019/reverse_proxy/upstreams >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    env_file:
      - ./envs/.envs-common

  database:
    image: georchestra/database:latest
    env_file:
      - ./envs/.envs-database-georchestra
    environment:
      - PGHOST=localhost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U georchestra"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
        window: 15m
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql
    restart: always

  ldap:
    image: georchestra/ldap:latest
    secrets:
      - slapd_password
    environment:
      - SLAPD_ORGANISATION=georchestra
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_PASSWORD_FILE=/run/secrets/slapd_password
      - SLAPD_PASSWORD=
      - SLAPD_LOG_LEVEL=32768 # See https://www.openldap.org/doc/admin24/slapdconfig.html#loglevel%20%3Clevel%3E
      - RUN_AS_UID=0
      - RUN_AS_GID=0
      - LDAPHOST=localhost
    env_file:
      - ./envs/.envs-ldap
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
    tmpfs:
      - /var/run/slapd
    restart: always

  smtp:
    image: camptocamp/exim:latest
    env_file:
      - ./envs/.envs-smtprelay
    volumes:
      - mail:/var/mail
      - mail_spool:/var/spool/exim4
    restart: always

  gateway:
    image: georchestra/gateway:latest-debug
    depends_on:
      - database
    volumes:
      - ./config:/etc/georchestra
    environment:
      - JAVA_TOOL_OPTIONS=-Dgeorchestra.datadir=/etc/georchestra
    env_file:
      - ./envs/.envs-common
      - ./envs/.envs-ldap
      - ./envs/.envs-hosts
      - ./envs/.envs-database-georchestra
    ports:
      - "8080:8080"

  console:
    image: georchestra/console:latest
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8080/console/account/new >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      - ldap
      - database
    volumes:
      - ./config:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF -Xms256m -Xmx512m
    env_file:
      - ./envs/.envs-common
      - ./envs/.envs-ldap
      - ./envs/.envs-database-georchestra
      - ./envs/.envs-hosts
    restart: always

  geoserver:
    image: georchestra/geoserver:latest
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f 'http://localhost:8080/geoserver/ows?SERVICE=WMS&LAYERS=geor:public_layer&FORMAT=image/png&VERSION=1.3.0&SLD_VERSION=1.1.0&REQUEST=GetMap&CRS=EPSG:3857&BBOX=-20820223,-20820223,20820223,20820223&WIDTH=10&HEIGHT=10' >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8g"
    depends_on:
      - ldap
      - database
    volumes:
      - ./config:/etc/georchestra
      - geoserver_datadir:/mnt/geoserver_datadir
      - geoserver_geodata:/mnt/geoserver_geodata
      - geoserver_tiles:/mnt/geoserver_tiles
      - geoserver_native_libs:/mnt/geoserver_native_libs
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF -Xms256m -Xmx8g -DGEOSERVER_CSRF_WHITELIST=georchestra-127-0-0-1.nip.io
    env_file:
      - ./envs/.envs-database-georchestra
      - ./envs/.envs-database-datafeeder
    restart: always

  geonetwork:
    image: georchestra/geonetwork:latest
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8080/geonetwork/srv/eng/catalog.search >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4g"
    depends_on:
      - console
      - database
      - elasticsearch
    volumes:
      - ./config:/etc/georchestra
      - geonetwork_datadir:/mnt/geonetwork_datadir
    environment:
      - JAVA_OPTIONS=-Duser.home=/tmp/jetty -Dgeorchestra.datadir=/etc/georchestra -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF -Xms256m -Xmx4g
    env_file:
      - ./envs/.envs-hosts
      - ./envs/.envs-database-georchestra
      - ./envs/.envs-elastic
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    deploy:
      resources:
        limits:
          cpus: "0"
          memory: "1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:$$ELASTIC_PASSWORD -s -f http://localhost:9200/_cat/health  >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    env_file:
      - ./envs/.envs-elastic
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    restart: always

  kibana:
    deploy:
      replicas: 0
    image: docker.elastic.co/kibana/kibana:8.14.3
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:5601/api/status >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    env_file:
      - ./envs/.envs-hosts
      - ./envs/.envs-elastic
    volumes:
      - ./resources/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always

  ogc-api-records:
    image: geonetwork/gn-cloud-ogc-api-records-service:4.4.7-0
    depends_on:
      - geonetwork
      - database
      - elasticsearch
    environment:
      LANG: en_US.UTF-8
      SERVER_SERVLET_CONTEXT_PATH: /ogc-api-records
      SPRING_CONFIG_LOCATION: file:///etc/georchestra/geonetwork/microservices/ogc-api-records/config.yml
      SPRING_PROFILES_ACTIVE: standalone
      JAVA_OPTS: -Dfile.encoding=UTF-8
    env_file:
      - ./envs/.envs-common
      - ./envs/.envs-hosts
      - ./envs/.envs-database-georchestra
      - ./envs/.envs-elastic
    volumes:
      - ./config:/etc/georchestra
    restart: always

  datahub:
    image: geonetwork/geonetwork-ui-datahub:latest
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:80/datahub/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      ASSETS_DIRECTORY_OVERRIDE: /etc/georchestra/datahub/assets
      CONFIG_DIRECTORY_OVERRIDE: /etc/georchestra/datahub/conf
      CUSTOM_SCRIPTS_DIRECTORY: /etc/georchestra/datahub/scripts
    volumes:
      - ./config:/etc/georchestra
    restart: always

  metadata-editor:
    image: geonetwork/geonetwork-ui-metadata-editor:latest
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:80/metadata-editor/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    environment:
      ASSETS_DIRECTORY_OVERRIDE: /etc/georchestra/metadata-editor/assets
      CONFIG_DIRECTORY_OVERRIDE: /etc/georchestra/metadata-editor/conf
      CUSTOM_SCRIPTS_DIRECTORY: /etc/georchestra/metadata-editor/scripts
    volumes:
      - ./config:/etc/georchestra
    restart: always

  mapstore:
    image: georchestra/mapstore:latest
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8080/mapstore/configs/config.json >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      - database
      - ldap
    volumes:
      - ./config:/etc/georchestra
      - mapstore_extensions:/mnt/mapstore_extensions
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m -Dgeorchestra.datadir=/etc/georchestra -Dgeorchestra.extensions=/mnt/mapstore_extensions -DPRINT_BASE_URL=pdf
    env_file:
      - ./envs/.envs-ldap
      - ./envs/.envs-database-georchestra
    restart: always

  postgis:
    # used by datafeeder to ingest uploaded user datasets into
    image: postgis/postgis:18-3.6-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 3s
      retries: 3
    env_file:
      - ./envs/.envs-database-datafeeder
    volumes:
      - datafeeder_postgis_data:/var/lib/postgresql
    restart: always

  datafeeder:
    image: georchestra/datafeeder:latest
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8080/datafeeder >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      - database
      - postgis
    volumes:
      - ./config:/etc/georchestra
      - datafeeder_uploads:/tmp/datafeeder
    environment:
      - JAVA_OPTIONS=-Xms512m -Xmx512m -Dspring.profiles.active=georchestra,data-api-schemas -Dspring.config.additional-location=file:/etc/georchestra/data-api/application.yaml
      # You can set a higher loglevel this way: (ref. https://docs.spring.io/spring-boot/docs/2.1.13.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-levels)
      - LOGGING_LEVEL_ORG_GEORCHESTRA_DATAFEEDER=INFO
    env_file:
      - ./envs/.envs-common
      - ./envs/.envs-hosts
      - ./envs/.envs-database-georchestra
      - ./envs/.envs-database-datafeeder
    restart: always

  import:
    image: georchestra/datafeeder-frontend:latest
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:80/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      - datafeeder
    environment:
      CUSTOM_SCRIPTS_DIRECTORY: /etc/georchestra/datafeeder/scripts/import
    volumes:
      - ./config:/etc/georchestra
    restart: always
